### ISSUE TITLE
phpstorm.sh is not founded

### ISSUE THREAD

**Issue by zhil** [sanduhrs/phpstorm-url-handler#9]
Using latest phpstorm, dont remember how did I installed it. phpstorm.sh is located in 
```
~/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/173.4548.32/bin/phpstorm.sh
```

it could be fixed by changing PATH folder, but I am pretty sure, that after phpstorm upgrade folder name would be changed. Not sure how to fix it, I just changed phpstorm-url-handler from
```
# Check if phpstorm|pstorm command exist.
if type phpstorm > /dev/null; then
    /usr/bin/env phpstorm --line "${line}" "${file}"
elif type pstorm > /dev/null; then
    /usr/bin/env pstorm --line "${line}" "${file}"
fi

```
to
```
/usr/bin/env ~/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/173.4548.32/bin/phpstorm.sh --line "${line}" "${file}"
```

Adding this issue just in case if somebody else cant make it work too.

**Comment by stephanvierkant** [comment]
I don't know how, but I'm sure a bash guru can fix this using `~/.local/share/applications/jetbrains-phpstorm.desktop`

**Comment by ThomasLandauer** [comment]
Instead of extracting the `Exec` line from `~/.local/share/applications/jetbrains-phpstorm.desktop`, I suggest:
1. Create a symlink of your `/home/thomas/.local/share/JetBrains/Toolbox/apps/PhpStorm/.../bin/phpstorm.sh` at `~/phpstorm.sh`
2. Add this line at the bottom of `/usr/bin/phpstorm-url-handler`:
    ```bash
    ~/phpstorm.sh --line "${line}" "${file}"
    ```
After upgrading PhpStorm, you need to update the symlink ;-)

**Comment by sanduhrs** [comment]
Please add the `phpstorm` executable to your `$PATH`:
https://github.com/sanduhrs/phpstorm-url-handler#installation
